# Generated by Django 4.1.2 on 2022-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Users\\Kalyibek\\PycharmProjects\\Samat_CO\\daam_ordo\\media'),
        ),
    ]
