# Generated by Django 4.1.2 on 2022-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_order_orderfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'оплачен'), ('new', 'новый заказ')], max_length=50, null=True),
        ),
    ]
