# Generated by Django 4.1.2 on 2022-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'оплачен'), ('new', 'новый заказ'), ('canceled', 'отменен')], max_length=50, null=True),
        ),
    ]
